version: '3.9'
services:
  market-gateway:
    build: ./market-gateway
    ports:
      - "8080:8080"
  market-client-service:
    build: ./market-client-service
    ports:
      - 80
      - 443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ./market-client-service/conf.d/https/:/https/